class LANGUAGE_DATA:
    menu=str()
    race=str()
    profile=str()
    single_player=str()
    quests=str()
    practice=str()
    language=str()
    english=str()
    latvian=str()
    records=str()
    win_count=str()
    lose_count=str()
    current_state=str()
    current_difficulty=str()
    current_streak=str()
    current_attempts=str()
    correct_answer_count=str()
    incorrect_answer_count=str()
    previous_correct_answer=str()
    submit=str()
    current_status=str()
    home=str()
    select_quest=str()
    quest=str()
    next=str()
    
